name: My test Workflow

on: [push]

jobs:
    #job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello, GitHub Actions"

    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:

      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y build-essential python3

      - run: pwd

      - name: Run test
        run: python3 test.py
   
